#!/usr/bin/env bash
# Generate a torrc for an exit relay from environment variables and run tor.
set -euo pipefail

TORRC=/var/lib/tor/torrc

# --- Guard rails -------------------------------------------------------------
# The Tor network rejects/flags relays without contact info, and exits without
# an abuse contact are irresponsible. Require it.
if [ -z "${TOR_CONTACT}" ]; then
  echo "ERROR: TOR_CONTACT is required. Set an abuse/ops contact, e.g." >&2
  echo "       -e TOR_CONTACT='tor-admin <abuse@example.org>'" >&2
  exit 1
fi

# --- Reduced exit policy (Tor Project recommended) ---------------------------
# Accepts common ports; rejects the noisy/abuse-heavy ones (e.g. SMTP/25 and
# file-sharing). Cuts down abuse complaints substantially vs the default policy.
reduced_exit_policy() {
  local ports="20-21 22 23 43 53 79-81 88 110 143 194 220 389 443 464 465 531 \
543-544 554 563 587 636 706 749 873 902-904 981 989-995 1194 1220 1293 1500 \
1533 1677 1723 1755 1863 2082-2083 2086-2087 2095-2096 2102-2104 3128 3389 \
3690 4321 4643 5050 5190 5222-5223 5228 5900 6660-6669 6679 6697 8000 8008 \
8074 8080 8082 8087-8088 8232-8233 8332-8333 8443 8888 9418 9999 11371 19294 \
19638 50002 64738"
  local p
  for p in $ports; do echo "ExitPolicy accept *:$p"; done
  echo "ExitPolicy reject *:*"
}

# --- Build torrc -------------------------------------------------------------
{
  echo "# Generated by entrypoint.sh $(date -u +%FT%TZ)"
  echo "Nickname ${TOR_NICKNAME}"
  echo "ContactInfo ${TOR_CONTACT}"
  echo "ORPort ${TOR_ORPORT}"
  echo "SocksPort 0"                 # relay: no local client proxy
  echo "DataDirectory /var/lib/tor"
  echo "User debian-tor"
  echo "Log notice stdout"
  echo "SafeLogging 1"               # never log client addresses/traffic
  echo "AvoidDiskWrites 1"

  [ "${TOR_DIRPORT}" != "0" ] && echo "DirPort ${TOR_DIRPORT}"

  case "${TOR_EXIT_POLICY}" in
    open)
      echo "ExitRelay 1"
      echo "IPv6Exit ${TOR_IPV6_EXIT}"
      # Tor's built-in default exit policy applies (broad). Higher abuse volume.
      ;;
    reduced)
      echo "ExitRelay 1"
      echo "IPv6Exit ${TOR_IPV6_EXIT}"
      reduced_exit_policy
      ;;
    middle|none)
      # Not an exit at all: relay traffic within the network only.
      echo "ExitRelay 0"
      echo "IPv6Exit 0"
      echo "ExitPolicy reject *:*"
      ;;
    *)
      echo "ERROR: TOR_EXIT_POLICY must be one of: reduced | open | middle" >&2
      exit 1
      ;;
  esac

  [ -n "${TOR_BANDWIDTH_RATE}" ]  && echo "RelayBandwidthRate ${TOR_BANDWIDTH_RATE}"
  [ -n "${TOR_BANDWIDTH_BURST}" ] && echo "RelayBandwidthBurst ${TOR_BANDWIDTH_BURST}"
  [ -n "${TOR_ACCOUNTING_MAX}" ]  && echo "AccountingMax ${TOR_ACCOUNTING_MAX}"

  [ -n "${TOR_EXTRA}" ] && printf '%s\n' "${TOR_EXTRA}"
} > "${TORRC}"

chown debian-tor:debian-tor "${TORRC}"

echo "[entrypoint] effective torrc:"
sed 's/^/    /' "${TORRC}"

# Validate config before launching.
tor -f "${TORRC}" --verify-config

echo "[entrypoint] starting tor (${TOR_EXIT_POLICY} policy)"
exec tor -f "${TORRC}"
